"""empty message

Revision ID: 91601875ad3a
Revises: 
Create Date: 2023-07-24 11:58:49.791176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91601875ad3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_names', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('playlist_names')

    # ### end Alembic commands ###
